### ISSUE TITLE
Allow customizing type names

### ISSUE THREAD

**Issue by krzema12** [krzema12/github-actions-typing#61]
Let's say we have an input:

```
   if_mention:
     type: list
     separator: ','
     list-item:
       type: enum
       allowed-values:
       - success
       - failure
       - cancelled
       - custom
       - always
```
Having a generated enum type named `IfMention` can look weird. Here we'd like to customize the generated class name somehow. This feature is already implemented in https://github.com/krzema12/github-workflows-kt (as a piece of internal API) and should eventually reach this typings library as well:

```diff
   if_mention:
     type: list
     separator: ','
     list-item:
       type: enum
+      name: MentionStatus
       allowed-values:
       - success
       - failure
       - cancelled
       - custom
       - always
```
